vision_model_params:
  embedding_dim: 768
  key_dim: 64
  num_head: 12
  patch_size: 16
  image_size: 224
  drop_out: 0.1
  num_layer: 12
  channel_size: 3

rpn_params:
  scales: [128, 256, 512]
  ascpect_ratios: [0.5, 1, 2]
  low_iou_threshold: 0.3
  high_iou_threshold: 0.7
  rpn_nms_threshold: 0.7
  rpn_batch_size: 256
  rpn_prenms_train_topk: 12000
  rpn_prenms_test_topk: 3000
  rpn_train_topk: 2000
  rpn_test_topk: 300
  input_channels: 768

roi_params:
  num_classes: 6
  roi_batch_size: 128
  fc_inner_dim: 1024
  roi_iou_threshold : 0.5
  roi_low_bg_iou : 0.0 
  roi_pool_size : 7
  roi_nms_threshold : 0.3
  roi_topk_detections : 100
  roi_score_threshold : 0.05
  roi_batch_size : 128
  roi_pos_fraction : 0.25


  